# Generated by Django 5.0.1 on 2024-01-12 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('publish_time', models.DateTimeField()),
                ('read_count', models.IntegerField()),
            ],
        ),
    ]
