# Generated by Django 5.0.1 on 2024-01-12 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='read_count',
            field=models.IntegerField(default=0),
        ),
    ]
