# Generated by Django 5.0.1 on 2024-02-15 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='Bio',
            field=models.CharField(default='Write about you so people know about you more', max_length=5000),
        ),
    ]
