# Generated by Django 5.0.1 on 2024-06-17 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_post_read_count_alter_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='App.bloguser'),
        ),
        migrations.DeleteModel(
            name='PostCategory',
        ),
    ]
