# Generated by Django 5.0.1 on 2024-02-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_authorfollower'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='profileImg',
            field=models.ImageField(default='/media/App/profileimg/profile.webp', upload_to='App/profileimg', verbose_name='Profile Image'),
        ),
    ]
