# Generated by Django 5.0.1 on 2024-01-16 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_post_read_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
