# Generated by Django 5.0.1 on 2024-03-20 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_postcategory_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thImg',
            field=models.ImageField(blank=True, default='', null=True, upload_to='App/thumbnail/', verbose_name='Post Thumbnail'),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='Bio',
            field=models.CharField(default='', max_length=5000, null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.postcategory', verbose_name='Post_Categories'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tags',
            field=models.ManyToManyField(blank=True, to='App.tag', verbose_name='Post_Tags'),
        ),
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.post')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.bloguser')),
            ],
        ),
    ]
