# Generated by Django 5.0.1 on 2024-03-20 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_post_thimg_alter_bloguser_bio_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.postcategory', verbose_name='Post_Categories'),
        ),
    ]
