# Generated by Django 5.0.1 on 2024-01-20 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_post_publish_time_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comments',
            new_name='comment_text',
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 20, 11, 32, 8, 811829)),
        ),
    ]
