# Generated by Django 5.0.1 on 2024-03-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_alter_post_category_alter_post_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='Bio',
            field=models.CharField(default='', max_length=5000, null=True),
        ),
    ]
