# Generated by Django 5.0.1 on 2024-03-09 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_alter_bloguser_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.postcategory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.bloguser')),
            ],
        ),
    ]
