# Generated by Django 5.0.1 on 2024-01-20 06:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_rename_comments_comment_comment_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 20, 11, 32, 23, 10159)),
        ),
    ]
