# Generated by Django 5.0.1 on 2024-03-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_alter_post_tags_alter_savedpost_saved_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thImg',
            field=models.ImageField(blank=True, default='', null=True, upload_to='App/thumbnail/', verbose_name='Post Thumbnail'),
        ),
    ]
