# Generated by Django 5.0.1 on 2024-01-31 16:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_comment_like_post_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_time',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
