# Generated by Django 5.0.1 on 2024-01-31 16:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_alter_post_publish_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='publish_time',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
