# Generated by Django 5.0.1 on 2024-04-06 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_bloguser_likedposts_bloguser_savedposts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='likedPosts',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='savedPosts',
            field=models.JSONField(default=dict),
        ),
    ]
