# Generated by Django 5.0.1 on 2024-02-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_alter_bloguser_profileimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='profileImg',
            field=models.ImageField(default='profile.jpg', upload_to='profileimg/', verbose_name='Profile Image'),
        ),
    ]
