# Generated by Django 5.0.1 on 2024-02-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_post_publish_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='isReaded',
            field=models.BooleanField(default=False),
        ),
    ]
