# Generated by Django 5.0.1 on 2024-05-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_bloguser_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='test',
        ),
    ]
