# Generated by Django 5.0.1 on 2024-02-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_post_isreaded'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='isLiked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='post',
            name='isLiked',
            field=models.BooleanField(default=False),
        ),
    ]
