# Generated by Django 5.0.1 on 2024-05-13 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_remove_bloguser_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloguser',
            name='test',
            field=models.CharField(default='', max_length=50),
        ),
    ]
