# Generated by Django 5.0.1 on 2024-02-12 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0019_bloguser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='Bio',
            field=models.CharField(default=None, max_length=5000),
        ),
    ]
